name: mem0-dev

services:
  mem0:
    build:
      context: ..  # Set context to parent directory (mem0 root)
      dockerfile: server/dev.Dockerfile
    ports:
      - "8888:8000"
    env_file:
      - .env.dev
    networks:
      - mem0_network
    volumes:
      - ./history:/app/server/history      # History db location
      - .:/app/server                      # Server code for hot reload
      - ../mem0:/app/mem0                  # Mem0 library for hot reload
      - ../mem0/memory/enhanced_memory.py:/app/mem0/memory/enhanced_memory.py  # Enhanced memory file
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  postgres:
    image: ankane/pgvector:v0.5.1
    restart: on-failure
    shm_size: "128mb"
    networks:
      - mem0_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "8432:5432"

  neo4j:
    image: neo4j:5.26.4
    networks:
      - mem0_network
    environment:
      - NEO4J_AUTH=neo4j/mem0graph
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "mem0graph", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "8474:7474" # HTTP
      - "8687:7687" # Bolt
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
  postgres_db:

networks:
  mem0_network:
    driver: bridge
